### PR TITLE
Started work on algorithm channel.

### PR DESCRIPTION
**Pull request by jaheba**
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**WIP**

---
Addresses: #218 

The idea is that customers can add a new data channel named `algorithm`.

In it, there is a `algorithm.json` file which can be used to setup a new algorithm on the fly.

### CODE REVIEW

**Comment by szha** [comment]
Job PR-221/2 is complete. 
Docs are uploaded to http://gluon-ts-staging.s3-accelerate.dualstack.amazonaws.com/PR-221/2/index.html

**Comment by aalexandrov** [comment]
I like the general idea, but I am not sure whether we should allow the execution of arbitrary bash commands through our codebase. 

A bit more robust is to have an explicit `entrypoint.sh` that 

- checks whether `/opt/ml/input/data/algorithm/setup.py` exists,
- if the above is true, runs `pip install .` from the enclosing folder, and
- delegates execution to `python -m gluonts.shell`.

Then we don't need a lot of extra Python code (clients can configure an `algorithm` channel and pass the `forecaster` value as part of the `hyperparameters.json`).

**Comment by jaheba** [comment]
Once thing I thought about is to add `algorithm` to ``sys.path``. That way, if you have a simple setup (like `my_algo.py`), you could just add `my_algo.MyEstimator` as the forecaster and things should just work.

I think if you actually want to add more complicated dependencies, you would create a new base-image first (e.g. if you were to add the R-forecaster that way).

**Comment by aalexandrov** [comment]
> Once thing I thought about is to add algorithm to `sys.path`.

I like that idea.

**Comment by szha** [comment]
Job PR-221/3 is complete. 
Docs are uploaded to http://gluon-ts-staging.s3-accelerate.dualstack.amazonaws.com/PR-221/3/index.html

**Pull request closed without merging**
